---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-10.18.2.box
  run_list:
  - recipe[apt]
- name: centos-6.3
  driver_config:
    box: opscode-centos-6.3
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.3.box

suites:
- name: carbon
  run_list:
  - recipe[graphite::carbon]
- name: carbon_runit
  run_list:
  - recipe[graphite::carbon_runit]
- name: carbon_runit_twistd
  run_list:
  - recipe[graphite::carbon_runit_twistd]
