driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.5
    run_list: apt::default
  - name: fedora-24
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
- name: default
  run_list:
  - recipe[runit]
  - recipe[graphite_example::single_node]
  attributes:
    graphite:
      listen_port: "8080"
      uwsgi:
        workers: 4
        listen_http: true
